### ISSUE TITLE
cannot define shipments

### ISSUE THREAD

**Issue by oblonski** [karussell/directions-api-vrp-java-client#5]

**Comment by karussell** [comment]
Why?

**Comment by oblonski** [comment]
Because there is no Shipment class in client. Obviously it is not yet in
the swagger spec or the client wasnt generated with the latest spec.

Am 21/05/15 um 11:00 schrieb Peter:

**Comment by oblonski** [comment]
see examples 
51732f37b6ab9f31841bc8472c64ece0467fbe03
