### ISSUE TITLE
rename package name io.swagger 

### ISSUE THREAD

**Issue by oblonski** [karussell/directions-api-vrp-java-client#6]
?

to com.graphhopper.vrp or .opt or ?

**Comment by karussell** [comment]
The [other APIs](https://github.com/graphhopper/directions-api-java-client/tree/master/src/main/java/com/graphhopper/api) are packaged under com.graphhopper.api so probably also this?

**Comment by oblonski** [comment]
thus com.graphhopper.api.vrp ? oder com.graphhopper.api.opt?

Am 22/05/15 um 09:35 schrieb Peter:

**Comment by karussell** [comment]
puh, don't know :) vrp?

**Comment by oblonski** [comment]
com.graphhopper.api.vrp
51732f37b6ab9f31841bc8472c64ece0467fbe03
