### ISSUE TITLE
push new version

### ISSUE THREAD

**Issue by oblonski** [karussell/directions-api-vrp-java-client#7]
How do I push a new version? Even a branch cannot be pushed. I thought that this is the way to push a pull request? I get this:

remote: Permission to karussell/directions-api-vrp-java-client.git denied to oblonski.
fatal: unable to access 'https://github.com/karussell/directions-api-vrp-java-client.git/': The requested URL returned error: 403

**Comment by oblonski** [comment]
probably I need to make the change on a fork ... oh nein

**Comment by oblonski** [comment]
this is what I did not have in mind

**Comment by karussell** [comment]
yes, but I've also enabled permission for you now

**Comment by oblonski** [comment]
perfect
51732f37b6ab9f31841bc8472c64ece0467fbe03
