### ISSUE TITLE
After adding this lib as dependency to Android app build fails

### ISSUE THREAD

**Issue by farmazon3000** [karussell/directions-api-vrp-java-client#8]
All my dependencies are like:

```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.google.android.gms:play-services:8.4.0'
    compile 'com.parse.bolts:bolts-tasks:1.3.0'
    compile 'com.parse:parse-android:1.12.0'
    compile 'com.graphhopper:directions-api-java-client:0.5.0.2'
    compile 'com.graphhopper:directions-api-vrp-java-client:0.5.0.1'
}
```

And build fails with:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/LICENSE
  	File1: /home/fr/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.4.2/6bb52af09372d5064206d47d7887d41671f00f7d/jackson-annotations-2.4.2.jar
  	File2: /home/fr/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.4.2/8e31266a272ad25ac4c089734d93e8d811652c1f/jackson-databind-2.4.2.jar
  	File3: /home/fr/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.4.2/ceb72830d95c512b4b300a38f29febc85bdf6e4b/jackson-core-2.4.2.jar


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by farmazon3000** [comment]
After adding those as proposed here http://stackoverflow.com/questions/33923461/how-do-i-resolve-duplicate-files-copied-in-apk-meta-inf

```
packagingOptions {
    exclude 'META-INF/DEPENDENCIES.txt'
    exclude 'META-INF/LICENSE.txt'
    exclude 'META-INF/NOTICE.txt'
    exclude 'META-INF/NOTICE'
    exclude 'META-INF/LICENSE'
    exclude 'META-INF/DEPENDENCIES'
    exclude 'META-INF/notice.txt'
    exclude 'META-INF/license.txt'
    exclude 'META-INF/dependencies.txt'
    exclude 'META-INF/LGPL2.1'
}
```

Another error occurs:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/services/javax.ws.rs.ext.MessageBodyReader
  	File1: /home/fr/.gradle/caches/modules-2/files-2.1/com.sun.jersey.contribs/jersey-multipart/1.18/73702df86c6d185ec98f827561df8fabe1ce2570/jersey-multipart-1.18.jar
  	File2: /home/fr/.gradle/caches/modules-2/files-2.1/com.sun.jersey/jersey-core/1.18/b3d0fde341fafdab2318602954218d38727f95cf/jersey-core-1.18.jar


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by farmazon3000** [comment]
I ended up adding new ```exclude```s and then compiling to figure out all excludes and it works when I have:

```
packagingOptions {
    exclude 'META-INF/DEPENDENCIES.txt'
    exclude 'META-INF/LICENSE.txt'
    exclude 'META-INF/NOTICE.txt'
    exclude 'META-INF/NOTICE'
    exclude 'META-INF/LICENSE'
    exclude 'META-INF/DEPENDENCIES'
    exclude 'META-INF/notice.txt'
    exclude 'META-INF/license.txt'
    exclude 'META-INF/dependencies.txt'
    exclude 'META-INF/LGPL2.1'
    exclude 'META-INF/services/javax.ws.rs.ext.MessageBodyReader'
    exclude 'META-INF/services/javax.ws.rs.ext.MessageBodyWriter'
    exclude 'META-INF/jersey-module-version'
    exclude 'META-INF/services/com.sun.jersey.spi.inject.InjectableProvider'
}
```

**Comment by karussell** [comment]
Hmmh, I have only few experience with Android&Gradle. Would you mind finding out which other package is using jersey?

**Comment by karussell** [comment]
Instead of excluding the MessageBody etc stuff would you instead try:
```
packagingOptions {
    pickFirst 'META-INF/services/javax.ws.rs.ext.MessageBodyReader'
    pickFirst 'META-INF/services/javax.ws.rs.ext.MessageBodyWriter'
    pickFirst 'META-INF/jersey-module-version'
    pickFirst 'META-INF/services/com.sun.jersey.spi.inject.InjectableProvider'
}
```

**Comment by karussell** [comment]
See issue here https://code.google.com/p/android/issues/detail?id=67878

**Comment by karussell** [comment]
If this is still not possible to fix you could try a different swagger java implementation. Currently we use [the default 'Java'](https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/Java) but we could try ['android'](https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/android)

**Comment by farmazon3000** [comment]
```pickFirst``` did not helped, I'll try with generating my own client.

**Comment by karussell** [comment]
If the client generated with 'android' fixes the problem and also runs under server side Java we'll move to this one.

**Comment by farmazon3000** [comment]
'android' fixes the problem - at least it's able to receive 500 from the server :). Maybe you can tell rhit away what's wrong with the JSON I send (it's produced by the (example code)[https://github.com/karussell/directions-api-vrp-java-client/blob/master/src/main/java/com/graphhopper/api/vrp/example/TSP_BiggestCitiesInGermanyByBikeExample.java]) 
[thisJSONgets500.txt](https://github.com/karussell/directions-api-vrp-java-client/files/82575/thisJSONgets500.txt)

**Comment by farmazon3000** [comment]
It returns 500 also when I curl (i.e. not from Android app):

```
curl -X POST -H "Content-Type: application/json" "https://graphhopper.com/api/1/vrp/optimize?key=..." --data @thisJSONgets500.txt
```

So it must be sth wrong with the JSON.

**Comment by karussell** [comment]
Thanks a lot for reporting - we'll fix asap! If you remove the shipments:null and relations:null in the JSON you get a valid response. We make sure our app does not throw a NPE in these cases to avoid fiddling with this!

**Comment by farmazon3000** [comment]
Yeah I've already figured out that shipments:null is a problem.

**Comment by karussell** [comment]
As #10 is now fixed and the android version seems to work now: would you mind to test if our tests would pass with this new implementation? Which means it will work also on server&desktop and we can safely switch to this implementation.

**Comment by karussell** [comment]
@farmazon3000 I discussed this with the swagger people [here](https://github.com/swagger-api/swagger-codegen/issues/1353) and would like to know: did you use the Android client?

**Comment by karussell** [comment]
This should be fixed now as we switched to the okhttp-gson template. Please see the new home: https://github.com/graphhopper/directions-api-java-client
